client_id = "0472e1133d4aa1fd30869ef83a9ed39d"
name = "Seesaw"
application_url = "https://seesawlive.com"
embedded = false

[access_scopes]
scopes = "read_products,read_orders,read_customers,read_inventory,read_locations"

[auth]
redirect_urls = [ "https://seesawlive.com/api/auth/shopify/callback" ]

[webhooks]
api_version = "2024-10"

  [webhooks.privacy_compliance]
  customer_data_request_url = "https://seesawlive.com/api/webhooks/shopify/customers-data-request"
  customer_deletion_url = "https://seesawlive.com/api/webhooks/shopify/customers-redact"
  shop_deletion_url = "https://seesawlive.com/api/webhooks/shopify/shop-redact"
